#pragma once

typedef enum {
  RPC_COMMAND_PING = 0xFF,

  RPC_COMMAND_HASH_MD5 = 0xF4,
  RPC_COMMAND_HASH_SHA256 = 0xF5,

  RPC_COMMAND_INITIALIZE_WALLET = 0xA0,
  RPC_COMMAND_RESTORE_WALLET = 0xA1,
  RPC_COMMAND_RESET_WALLET = 0xA2,

  RPC_COMMAND_GET_WALLET_STATUS = 0xA3,
  RPC_COMMAND_GET_ADDRESS = 0xA4,
  RPC_COMMAND_GET_PUBLIC_KEY = 0xA5,

  RPC_COMMAND_SIGN_TRANSACTION = 0xA6,

} rpc_command_t;
