#pragma once

typedef enum {
  SMARTCARD_INITIALIZE_WALLET = 0x00,
  SMARTCARD_RESET_WALLET,

  SMARTCARD_GET_WALLET_STATUS,
  SMARTCARD_GET_ADDRESS,
  SMARTCARD_GET_PUBLIC_KEY,

  SMARTCARD_SIGN_TRANSACTION,
} smartcard_command_t;
