#pragma once

typedef enum {
  SMARTCARD_INITIALIZE_WALLET = 0x00,
  SMARTCARD_RESET_WALLET = 0xFF,

  SMARTCARD_GET_WALLET_STATUS = 0x02,
  SMARTCARD_GET_ADDRESS = 0x03,
  SMARTCARD_GET_PUBLIC_KEY = 0x04,

  SMARTCARD_SIGN_TRANSACTION = 0x05,
} smartcard_command_t;
