#ifndef _APDU_COMMANDS_H_
#define _APDU_COMMANDS_H_

enum APDU_INS {
  APDU_INS_HASH_MD5 = 0xF4,
  APDU_INS_HASH_SHA256 = 0xF5,

  APDU_INS_GENERATE_WALLET = 0xA0,
};

// enum APDU_P1_HASH_TYPE {
//   APDU_P1_MD5 = 0x01,
//   APDU_P1_SHA256 = 0x02,
// };

#endif /* _APDU_COMMANDS_H_ */
